services:
  condor-notebook:
    build: .
    ports:
      - "127.0.0.1:9619:9618"   # HTCondor collector
      - "127.0.0.1:8866:8866"   # Voilà UI
    volumes:
      - .:/home/htcondor/notebook
      - ./condor_config.local:/etc/condor/condor_config.local:ro
    # We rely on your Dockerfile's ENTRYPOINT to start Condor -> Voilà
